QT.gui_private.VERSION = 5.8.0
QT.gui_private.MAJOR_VERSION = 5
QT.gui_private.MINOR_VERSION = 8
QT.gui_private.PATCH_VERSION = 0
QT.gui_private.name = QtGui
QT.gui_private.module =
QT.gui_private.libs = $$QT_MODULE_LIB_BASE
QT.gui_private.includes = $$QT_MODULE_INCLUDE_BASE/QtGui/5.8.0 $$QT_MODULE_INCLUDE_BASE/QtGui/5.8.0/QtGui
QT.gui_private.frameworks =
QT.gui_private.depends = core_private gui
QT.gui_private.uses =
QT.gui_private.module_config = v2 internal_module
QT.gui_private.enabled_features = directwrite freetype system-freetype fontconfig gif harfbuzz ico jpeg multiprocess png system-harfbuzz system-jpeg system-png
QT.gui_private.disabled_features = xcb accessibility-atspi-bridge android-style-assets direct2d directfb directwrite2 egl egl_x11 eglfs eglfs_brcm eglfs_egldevice eglfs_gbm eglfs_mali eglfs_viv eglfs_viv_wl evdev integrityfb libinput libinput-axis-api linuxfb mirclient mtdev system-xcb tslib xinput2 xkb xkbcommon-evdev xlib xrender
QMAKE_LIBS_OPENGL = -lopengl32
QMAKE_LIBS_FREETYPE = -lfreetype
QMAKE_INCDIR_FREETYPE = /home/gregwar/git/mxe/usr/i686-w64-mingw32.shared.posix/include/harfbuzz //home/gregwar/git/mxe/usr/i686-w64-mingw32.shared.posix/include/cairo //home/gregwar/git/mxe/usr/i686-w64-mingw32.shared.posix/include/pixman-1 /home/gregwar/git/mxe/usr/i686-w64-mingw32.shared.posix/include/freetype2 /home/gregwar/git/mxe/usr/i686-w64-mingw32.shared.posix/include //home/gregwar/git/mxe/usr/i686-w64-mingw32.shared.posix/include/libpng16 //home/gregwar/git/mxe/usr/i686-w64-mingw32.shared.posix/include/glib-2.0 //home/gregwar/git/mxe/usr/i686-w64-mingw32.shared.posix/lib/glib-2.0/include //home/gregwar/git/mxe/usr/i686-w64-mingw32.shared.posix/include
QMAKE_LIBS_FONTCONFIG = -lfontconfig -lfreetype
QMAKE_INCDIR_FONTCONFIG = /home/gregwar/git/mxe/usr/i686-w64-mingw32.shared.posix/include/harfbuzz //home/gregwar/git/mxe/usr/i686-w64-mingw32.shared.posix/include/cairo //home/gregwar/git/mxe/usr/i686-w64-mingw32.shared.posix/include/pixman-1 /home/gregwar/git/mxe/usr/i686-w64-mingw32.shared.posix/include/freetype2 /home/gregwar/git/mxe/usr/i686-w64-mingw32.shared.posix/include //home/gregwar/git/mxe/usr/i686-w64-mingw32.shared.posix/include/libpng16 //home/gregwar/git/mxe/usr/i686-w64-mingw32.shared.posix/include/glib-2.0 //home/gregwar/git/mxe/usr/i686-w64-mingw32.shared.posix/lib/glib-2.0/include //home/gregwar/git/mxe/usr/i686-w64-mingw32.shared.posix/include
QMAKE_LIBS_HARFBUZZ = -lharfbuzz
QMAKE_LIBS_LIBJPEG = -ljpeg
QMAKE_LIBS_LIBPNG = -lpng16
QMAKE_INCDIR_LIBPNG = //home/gregwar/git/mxe/usr/i686-w64-mingw32.shared.posix/include/libpng16
